name: Clean Deploy to GAS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install clasp
      run: npm install -g @google/clasp
      
    - name: Setup clasp auth
      run: echo '${{ secrets.CLASPRC_JSON }}' > ~/.clasprc.json
        
    - name: Clear GAS and deploy clean
      run: |
        # Pull current GAS project
        clasp pull --rootDir ./temp
        
        # Delete all files except appsscript.json
        find ./temp -type f ! -name "appsscript.json" -delete
        clasp push --rootDir ./temp --force
        
        # Deploy fresh files
        clasp push --rootDir ./src --force
        echo "✅ Clean deployment completed"