# ワークフローの名前
name: CI and Deploy to GAS

# ワークフローが実行されるタイミング
on:
  # 'main' ブランチに push された時にデプロイを実行
  push:
    branches:
      - main # ※ご自身のメインブランチが 'master' の場合は書き換えてください
    paths:
      - 'src/**'
      - '.github/workflows/**' # ワークフロー自体の変更でも実行

  # 'main' ブランチへのプルリクエストが作成/更新された時にテストを実行
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/**'

  # GitHubの画面から手動で実行することも可能にする
  workflow_dispatch:

jobs:
  # ジョブの名前を、役割がわかりやすいように変更
  ci-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリのコードをチェックアウトします
      #    - v4に更新。pushイベントの際、後続のステップでPR番号を見つけるために全履歴を取得します
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Node.js環境をセットアップします
      #    - v4に更新し、キャッシュを有効化して高速化します
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3. 依存パッケージをインストールします
      #    - このステップはPRでもpushでも実行され、ビルド可能かを確認します
      - name: Install dependencies
        run: npm ci

      # --- ここから下は、mainブランチへのpush（マージ後）の時だけ実行される ---

      # 4. Google Apps Scriptへの認証を設定します
      #    - `clasp login` は使わず、認証ファイルを直接作成する方がCIでは確実です
      #    - 注意: このステップには、リポジトリのSecretsに `CLASPRC_JSON` の設定が必須です
      - name: Create clasprc.json for authentication
        if: github.event_name == 'push'
        run: echo '${{ secrets.CLASPRC_JSON }}' > ~/.clasprc.json # シークレット名もわかりやすいものに変更

      # 5. GASプロジェクトにコードをプッシュします
      #    - 注意: リポジトリのルートに `scriptId` を含む `.clasp.json` ファイルが必要です
      #    - `--force` オプションで、ローカルの状態とサーバーを完全に同期させます
      - name: Push to Apps Script
        if: github.event_name == 'push'
        run: npm run push -- --force

      # --- ここからがマージ後の結果を通知するステップ ---

      # 6. マージされたPR番号を特定します
      - name: Find Pull Request
        if: github.event_name == 'push'
        uses: peter-evans/find-pull-request@v3
        id: find-pr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-sha: ${{ github.sha }}
          branch: main

      # 7. デプロイ成功をPRにコメントします
      - name: Comment on PR (Success)
        if: success() && github.event_name == 'push' && steps.find-pr.outputs.number
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.find-pr.outputs.number }},
              body: '✅ **デプロイ成功**\n\nGoogle Apps Scriptへのプッシュが正常に完了しました。'
            })

      # 8. デプロイ失敗をPRにコメントします
      - name: Comment on PR (Failure)
        if: failure() && github.event_name == 'push' && steps.find-pr.outputs.number
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.find-pr.outputs.number }},
              body: '❌ **デプロイ失敗**\n\nGoogle Apps Scriptへのプッシュ中にエラーが発生しました。詳細は [Actionsのログ](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) を確認してください。'
            })
